name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - run: |
          content=$(cat package.json)
          echo "$content" | jq 'del(.scripts.postinstall)' > package.json
      
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile --prod

      - run: pnpm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest 
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4